<?php
return [
    [
        'title' => 'SIP',
        'category' => 'investment',
        'description' => 'Calculate how much you need to save or how much you will accumulate with your SIP',
        'href' => 'sip-calculator.php',
        'image' => '../assets/images/sip.png',
    ],
    [
        'title' => 'Lumpsum',
        'category' => 'investment',
        'description' => 'Calculate returns for lumpsum investments to achieve your financial goals',
        'href' => 'lumpsum-calculator.php',
        'image' => '../assets/images/lumpsum.png',
    ],
    [
        'title' => 'Mutual Fund',
        'category' => 'investment',
        'description' => 'Calculate the returns on your mutual fund investments',
        'href' => 'mutual-fund-calculator.php',
        'image' => '../assets/images/financial-analysis-rupee-illustration.png',
    ],
    [
        'title' => 'CAGR',
        'category' => 'investment',
        'description' => 'Calculate compound annual growth rate for your investments',
        'href' => 'cagr-calculator.php',
        'image' => '../assets/images/cagr.png',
    ],
    [
        'title' => 'Step Up SIP',
        'category' => 'investment',
        'description' => 'Calculate SIP growth with an annual increase in investment amount',
        'href' => 'step-up-sip-calculator.php',
        'image' => '../assets/images/step-up-sip.png',
    ],
    [
        'title' => 'ETF',
        'category' => 'investment',
        'description' => 'Estimate ETF investment returns after expenses and trading costs',
        'href' => 'etf-calculator.php',
        'image' => '../assets/images/stoks-illustration.png',
    ],
    [
        'title' => 'SWP',
        'category' => 'retirement',
        'description' => 'Calculate your final amount with Systematic Withdrawal Plans (SWP)',
        'href' => 'swp-calculator.php',
        'image' => '../assets/images/fund.png',
    ],
    [
        'title' => 'SSY',
        'category' => 'retirement',
        'description' => 'Calculate returns for Sukanya Samriddhi Yojana (SSY) as per your investment',
        'href' => 'ssy-calculator.php',
        'image' => '../assets/images/sukanya-samriddhi-yojana.png',
    ],
    [
        'title' => 'PPF',
        'category' => 'retirement',
        'description' => 'Calculate your returns on Public Provident Fund (PPF)',
        'href' => 'ppf-calculator.php',
        'image' => '../assets/images/ppf.png',
    ],
    [
        'title' => 'EPF',
        'category' => 'retirement',
        'description' => 'Calculate returns for your Employee\'s Provident Fund (EPF)',
        'href' => 'epf-calculator.php',
        'image' => '../assets/images/epf.png',
    ],
    [
        'title' => 'ELSS',
        'category' => 'tax',
        'description' => 'Estimate ELSS returns and tax-saving investment outcomes',
        'href' => 'elss-calculator.php',
        'image' => '../assets/images/fund.png',
    ],
    [
        'title' => 'NSC',
        'category' => 'tax',
        'description' => 'Calculate National Savings Certificate maturity and interest',
        'href' => 'nsc-calculator.php',
        'image' => '../assets/images/fund.png',
    ],
    [
        'title' => 'STCG',
        'category' => 'tax',
        'description' => 'Calculate short-term capital gains tax on investments',
        'href' => 'stcg-calculator.php',
        'image' => '../assets/images/financial-analysis-rupee-illustration.png',
    ],
    [
        'title' => 'Brokerage',
        'category' => 'trading',
        'description' => 'Estimate brokerage, statutory charges, taxes, and net trading cost',
        'href' => 'brokerage-calculator.php',
        'image' => '../assets/images/stoks-illustration.png',
    ],
    [
        'title' => 'Margin',
        'category' => 'trading',
        'description' => 'Review indicative margin needs before placing trades',
        'href' => 'margin-calculator.php',
        'image' => '../assets/images/financial-analysis-monochrome-blue.png',
    ],
    [
        'title' => 'MTF',
        'category' => 'trading',
        'description' => 'Estimate margin trading facility cost, borrowing, and returns',
        'href' => 'mtf-calculator.php',
        'image' => '../assets/images/indian-mobile-investing-illustration.png',
    ],
    [
        'title' => 'Fixed Deposit',
        'category' => 'interest',
        'description' => 'Check returns on your fixed deposits (FDs) without any hassle',
        'href' => 'fd-calculator.php',
        'image' => '../assets/images/interest-savings-illustration.png',
    ],
    [
        'title' => 'Recurring Deposit',
        'category' => 'interest',
        'description' => 'Calculate recurring deposit maturity value with monthly deposits',
        'href' => 'rd-calculator.php',
        'image' => '../assets/images/interest-savings-illustration.png',
    ],
    [
        'title' => 'Post Office FD',
        'category' => 'interest',
        'description' => 'Estimate maturity value for post office fixed deposits',
        'href' => 'post-office-fd-calculator.php',
        'image' => '../assets/images/financial-analysis-without-ring.png',
    ],
    [
        'title' => 'Post Office RD',
        'category' => 'interest',
        'description' => 'Calculate 5-year post office recurring deposit returns',
        'href' => 'post-office-rd-calculator.php',
        'image' => '../assets/images/financial-analysis-monochrome-blue.png',
    ],
    [
        'title' => 'Simple Interest',
        'category' => 'interest',
        'description' => 'Calculate simple interest on loans and deposits',
        'href' => 'simple-interest-calculator.php',
        'image' => '../assets/images/interest-savings-illustration.png',
    ],
    [
        'title' => 'Compound Interest',
        'category' => 'interest',
        'description' => 'Understand compounding and estimate future value',
        'href' => 'compound-interest-calculator.php',
        'image' => '../assets/images/rupee-recurring-returns-illustration.png',
    ],
];
